import { AIMessage, ToolMessage } from '@langchain/core/messages';
import { tool } from '@langchain/core/tools';
import { z } from 'zod';
import { ToolNode } from '../ToolNode';
import { ChartRunRegistry } from '../ChartRunRegistry';

type BecauseResult = string;

const indicatorConfig = {
  configurable: {
    auto_chart: true,
    chart_config: {
      preset: 'indicator',
      input_mode: 'simple',
      max_charts: 1,
    },
    requestBody: { text: '查询指标趋势' },
  },
};

function makeBecauseTool(result: BecauseResult) {
  return tool(async () => result, {
    name: 'because_jn',
    description: 'test data tool',
    schema: z.object({
      command: z.string(),
      arguments: z.string().optional(),
    }),
  });
}

function makeEchartsTool(
  invoke: (params: Record<string, unknown>) => Promise<string>
) {
  return tool(invoke, {
    name: 'echarts_generator_app',
    description: 'test chart tool',
    schema: z.object({
      charts: z.union([z.array(z.record(z.string(), z.any())), z.string()]),
      _autoGenerated: z.union([z.boolean(), z.string()]).optional(),
    }),
  });
}

function dataCall(command = 'sql-executor', id = 'call_data') {
  return new AIMessage({
    content: '',
    tool_calls: [
      {
        id,
        name: 'because_jn',
        args: { command, arguments: '{}' },
      },
    ],
  });
}

function makeAskDataTool(result: string) {
  return tool(async () => result, {
    name: 'ask_data_mcp_test',
    description: 'test DAT data tool',
    schema: z.object({ query: z.string() }),
  });
}

function askDataCall() {
  return new AIMessage({
    content: '',
    tool_calls: [
      {
        id: 'call_dat',
        name: 'ask_data_mcp_test',
        args: { query: '查询指标' },
      },
    ],
  });
}

describe('ToolNode indicator auto-chart', () => {
  it('executes the server-side chart tool after deterministic auto success', async () => {
    const chartInvoke = jest.fn(async (params: Record<string, unknown>) =>
      JSON.stringify({
        success: true,
        charts: params.charts,
        echartdata: params.charts,
      })
    );
    const toolNode = new ToolNode({
      tools: [
        makeBecauseTool(
          JSON.stringify({
            success: true,
            rows: [
              { data_dt: '2026-01', index_value: 100 },
              { data_dt: '2026-02', index_value: 120 },
            ],
            columns: ['data_dt', 'index_value'],
          })
        ),
        makeEchartsTool(chartInvoke),
      ],
      dispatchSyntheticToolCall: async () => 'step_chart',
    });

    const result = (await toolNode.invoke(
      { messages: [dataCall()] },
      indicatorConfig
    )) as { messages: ToolMessage[] };

    expect(result.messages).toHaveLength(1);
    expect(chartInvoke).toHaveBeenCalledTimes(1);
    expect(chartInvoke.mock.calls[0][0]).toMatchObject({
      _autoGenerated: true,
    });
  });

  it('does not dispatch the same automatic chart twice when the data call re-enters the node', async () => {
    const chartInvoke = jest.fn(async (params: Record<string, unknown>) =>
      JSON.stringify({
        success: true,
        charts: params.charts,
        echartdata: params.charts,
      })
    );
    const toolNode = new ToolNode({
      tools: [
        makeBecauseTool(
          JSON.stringify({
            success: true,
            rows: [
              { data_dt: '2026-01', index_value: 100 },
              { data_dt: '2026-02', index_value: 120 },
            ],
          })
        ),
        makeEchartsTool(chartInvoke),
      ],
      chartRunRegistry: new ChartRunRegistry(),
      dispatchSyntheticToolCall: async () => 'step_chart',
    });

    await toolNode.invoke({ messages: [dataCall()] }, indicatorConfig);
    await toolNode.invoke({ messages: [dataCall()] }, indicatorConfig);

    expect(chartInvoke).toHaveBeenCalledTimes(1);
  });

  it('rejects a model chart that stringifies charts and claims to be auto-generated', async () => {
    const chartInvoke = jest.fn(async (params: Record<string, unknown>) =>
      JSON.stringify({ success: true, charts: params.charts })
    );
    const toolNode = new ToolNode({
      tools: [makeEchartsTool(chartInvoke)],
      chartRunRegistry: new ChartRunRegistry(),
    });
    const modelCall = new AIMessage({
      content: '',
      tool_calls: [
        {
          id: 'model_fake_auto',
          name: 'echarts_generator_app',
          args: {
            charts: JSON.stringify([
              {
                id: 'fake',
                role: 'indicator',
                type: 'bar',
                data: [{ org_name: 'unrelated', index_value: 5448.22 }],
                xField: 'org_name',
                yFields: ['index_value'],
                title: '错误图表',
              },
            ]),
            _autoGenerated: 'True',
          },
        },
      ],
    });

    const result = (await toolNode.invoke(
      { messages: [modelCall] },
      {
        configurable: {
          auto_chart: true,
          chart_config: {
            preset: 'indicator',
            input_mode: 'simple',
            max_charts: 1,
            hide_from_model: true,
          },
        },
      }
    )) as { messages: ToolMessage[] };

    expect(chartInvoke).not.toHaveBeenCalled();
    expect(JSON.parse(result.messages[0].content as string)).toMatchObject({
      success: false,
      skipped: true,
    });
  });

  it('still executes a server automatic chart when the tool is hidden from the model', async () => {
    const chartInvoke = jest.fn(async (params: Record<string, unknown>) =>
      JSON.stringify({ success: true, charts: params.charts })
    );
    const toolNode = new ToolNode({
      tools: [
        makeBecauseTool(
          JSON.stringify({
            success: true,
            rows: [
              { data_dt: '2026-01', index_value: 100 },
              { data_dt: '2026-02', index_value: 120 },
            ],
          })
        ),
        makeEchartsTool(chartInvoke),
      ],
      chartRunRegistry: new ChartRunRegistry(),
      dispatchSyntheticToolCall: async () => 'step_chart',
    });

    await toolNode.invoke(
      { messages: [dataCall()] },
      {
        configurable: {
          ...indicatorConfig.configurable,
          chart_config: {
            ...indicatorConfig.configurable.chart_config,
            hide_from_model: true,
          },
        },
      }
    );

    expect(chartInvoke).toHaveBeenCalledTimes(1);
  });

  it('uses current query rows when a hidden model chart is submitted beside the data call', async () => {
    const currentRows = [
      { brchna: '机构A', index_value: 1.1793, mea_unit: '万元' },
      { brchna: '机构B', index_value: 32.44037, mea_unit: '万元' },
      { brchna: '机构C', index_value: 8.5, mea_unit: '万元' },
    ];
    const chartInvoke = jest.fn(async (params: Record<string, unknown>) =>
      JSON.stringify({ success: true, charts: params.charts })
    );
    const toolNode = new ToolNode({
      tools: [
        makeBecauseTool(JSON.stringify({ success: true, rows: currentRows })),
        makeEchartsTool(chartInvoke),
      ],
      chartRunRegistry: new ChartRunRegistry(),
      dispatchSyntheticToolCall: async () => 'step_chart',
    });
    const combinedCall = new AIMessage({
      content: '',
      tool_calls: [
        {
          id: 'call_current_data',
          name: 'because_jn',
          args: { command: 'sql-executor', arguments: '{}' },
        },
        {
          id: 'call_stale_model_chart',
          name: 'echarts_generator_app',
          args: {
            charts: JSON.stringify([
              {
                id: 'stale',
                role: 'indicator',
                type: 'bar',
                data: [
                  { brchna: '旧机构A', index_value: 172.03 },
                  { brchna: '旧机构B', index_value: 184.19 },
                  { brchna: '旧机构C', index_value: 216.77 },
                ],
                xField: 'brchna',
                yFields: ['index_value'],
                title: '旧数据图表',
              },
            ]),
            _autoGenerated: 'True',
          },
        },
      ],
    });

    await toolNode.invoke(
      { messages: [combinedCall] },
      {
        configurable: {
          auto_chart: true,
          chart_config: {
            preset: 'indicator',
            input_mode: 'simple',
            max_charts: 1,
            hide_from_model: true,
            match_rules: {
              dimension_compare: { chart_type: 'bar' },
            },
          },
        },
      }
    );

    expect(chartInvoke).toHaveBeenCalledTimes(1);
    const generated = chartInvoke.mock.calls[0][0] as {
      charts: Array<{ data: Array<Record<string, unknown>> }>;
      _autoGenerated: boolean;
    };
    expect(generated._autoGenerated).toBe(true);
    expect(generated.charts[0].data).toEqual([
      currentRows[1],
      currentRows[2],
      currentRows[0],
    ]);
  });

  it('applies max_charts to stringified model chart payloads', async () => {
    const chartInvoke = jest.fn(async (params: Record<string, unknown>) =>
      JSON.stringify({ success: true, charts: params.charts })
    );
    const registry = new ChartRunRegistry();
    registry.register('default', 'current', {
      chartId: 'existing_auto',
      role: 'indicator',
      source: 'server_auto',
    });
    const toolNode = new ToolNode({
      tools: [makeEchartsTool(chartInvoke)],
      chartRunRegistry: registry,
    });
    const modelCall = new AIMessage({
      content: '',
      tool_calls: [
        {
          id: 'model_string_chart',
          name: 'echarts_generator_app',
          args: {
            charts: JSON.stringify([
              {
                id: 'duplicate',
                role: 'indicator',
                type: 'bar',
                title: '重复图',
              },
            ]),
          },
        },
      ],
    });

    const result = (await toolNode.invoke(
      { messages: [modelCall] },
      { configurable: { chart_config: { max_charts: 1 } } }
    )) as { messages: ToolMessage[] };

    expect(chartInvoke).not.toHaveBeenCalled();
    expect(JSON.parse(result.messages[0].content as string)).toMatchObject({
      success: false,
      skipped: true,
    });
  });

  it('does not register a rejected duplicate synthetic step for another data call', async () => {
    const chartInvoke = jest.fn(async (params: Record<string, unknown>) =>
      JSON.stringify({
        success: true,
        charts: params.charts,
        echartdata: params.charts,
      })
    );
    const dispatchSyntheticToolCall = jest.fn(async () => 'step_chart');
    const toolNode = new ToolNode({
      tools: [
        makeBecauseTool(
          JSON.stringify({
            success: true,
            rows: [
              { data_dt: '2026-01', index_value: 100 },
              { data_dt: '2026-02', index_value: 120 },
            ],
          })
        ),
        makeEchartsTool(chartInvoke),
      ],
      chartRunRegistry: new ChartRunRegistry(),
      dispatchSyntheticToolCall,
    });

    await toolNode.invoke(
      { messages: [dataCall('sql-executor', 'call_1')] },
      indicatorConfig
    );
    await toolNode.invoke(
      { messages: [dataCall('sql-executor', 'call_2')] },
      indicatorConfig
    );

    expect(chartInvoke).toHaveBeenCalledTimes(1);
    expect(dispatchSyntheticToolCall).toHaveBeenCalledTimes(1);
  });

  it('continues automatic chart ids from the conversation offset', async () => {
    const chartInvoke = jest.fn(async (params: Record<string, unknown>) =>
      JSON.stringify({
        success: true,
        charts: params.charts,
        echartdata: params.charts,
      })
    );
    const toolNode = new ToolNode({
      tools: [
        makeBecauseTool(
          JSON.stringify({
            success: true,
            rows: [
              { data_dt: '2026-01', index_value: 100 },
              { data_dt: '2026-02', index_value: 120 },
            ],
          })
        ),
        makeEchartsTool(chartInvoke),
      ],
      dispatchSyntheticToolCall: async () => 'step_chart',
    });

    await toolNode.invoke(
      { messages: [dataCall()] },
      {
        ...indicatorConfig,
        configurable: {
          ...indicatorConfig.configurable,
          chart_id_offset: 3,
        },
      }
    );

    expect(chartInvoke.mock.calls[0][0]).toMatchObject({
      charts: [expect.objectContaining({ id: 'chart_4' })],
      _autoGenerated: true,
    });
  });

  it('uses a stable session-scoped id when conversationId is available', async () => {
    const chartInvoke = jest.fn(async (params: Record<string, unknown>) =>
      JSON.stringify({
        success: true,
        charts: params.charts,
        echartdata: params.charts,
      })
    );
    const toolNode = new ToolNode({
      tools: [
        makeBecauseTool(
          JSON.stringify({
            success: true,
            rows: [
              { data_dt: '2026-01', index_value: 100 },
              { data_dt: '2026-02', index_value: 120 },
            ],
          })
        ),
        makeEchartsTool(chartInvoke),
      ],
      dispatchSyntheticToolCall: async () => 'step_chart',
    });

    await toolNode.invoke(
      { messages: [dataCall()] },
      {
        ...indicatorConfig,
        configurable: {
          ...indicatorConfig.configurable,
          chart_index_offset: 2,
          requestBody: {
            text: '查询指标趋势',
            conversationId: 'conversation-123',
          },
        },
      }
    );

    const chart = (
      chartInvoke.mock.calls[0][0] as { charts: Array<{ id: string }> }
    ).charts[0];
    expect(chart.id).toBe('zb_5c01549bf7a1390c_2');
  });

  it('skips chart generation when the successful data result cannot be parsed', async () => {
    const chartInvoke = jest.fn(async () => JSON.stringify({ success: true }));
    const toolNode = new ToolNode({
      tools: [makeBecauseTool('not-json'), makeEchartsTool(chartInvoke)],
      dispatchSyntheticToolCall: async () => 'step_chart',
    });

    await toolNode.invoke({ messages: [dataCall()] }, indicatorConfig);

    expect(chartInvoke).not.toHaveBeenCalled();
  });

  it('skips chart generation for malformed DAT ask_data output', async () => {
    const chartInvoke = jest.fn(async () => JSON.stringify({ success: true }));
    const toolNode = new ToolNode({
      tools: [
        makeAskDataTool('Query Results: not-json'),
        makeEchartsTool(chartInvoke),
      ],
      dispatchSyntheticToolCall: async () => 'step_chart',
    });

    await toolNode.invoke({ messages: [askDataCall()] }, indicatorConfig);

    expect(chartInvoke).not.toHaveBeenCalled();
  });

  it('skips chart generation when parsed rows have no chartable values', async () => {
    const chartInvoke = jest.fn(async () => JSON.stringify({ success: true }));
    const toolNode = new ToolNode({
      tools: [
        makeBecauseTool(
          JSON.stringify({
            success: true,
            rows: [{ label: 'only text' }],
            columns: ['label'],
          })
        ),
        makeEchartsTool(chartInvoke),
      ],
      dispatchSyntheticToolCall: async () => 'step_chart',
    });

    await toolNode.invoke({ messages: [dataCall()] }, indicatorConfig);

    expect(chartInvoke).not.toHaveBeenCalled();
  });

  it('does not generate a chart when the matched rule is intentionally disabled', async () => {
    const chartInvoke = jest.fn(async () => JSON.stringify({ success: true }));
    const toolNode = new ToolNode({
      tools: [
        makeBecauseTool(
          JSON.stringify({
            success: true,
            rows: [
              { org_name: 'A', index_value: 10 },
              { org_name: 'B', index_value: 20 },
            ],
          })
        ),
        makeEchartsTool(chartInvoke),
      ],
      dispatchSyntheticToolCall: async () => 'step_chart',
    });

    await toolNode.invoke(
      { messages: [dataCall()] },
      {
        ...indicatorConfig,
        configurable: {
          ...indicatorConfig.configurable,
          chart_config: {
            ...indicatorConfig.configurable.chart_config,
            match_rules: { dimension_compare: { enabled: false } },
          },
        },
      }
    );

    expect(chartInvoke).not.toHaveBeenCalled();
  });

  it('does not retry when the chart generator itself fails', async () => {
    const chartInvoke = jest.fn(async () =>
      JSON.stringify({ success: false, error: 'generator failed' })
    );
    const toolNode = new ToolNode({
      tools: [
        makeBecauseTool(
          JSON.stringify({
            success: true,
            rows: [
              { data_dt: '2026-01', index_value: 100 },
              { data_dt: '2026-02', index_value: 120 },
            ],
          })
        ),
        makeEchartsTool(chartInvoke),
      ],
      dispatchSyntheticToolCall: async () => 'step_chart',
    });

    await toolNode.invoke({ messages: [dataCall()] }, indicatorConfig);

    expect(chartInvoke).toHaveBeenCalledTimes(1);
  });

  it('does not generate a chart for an explicit SQL execution failure', async () => {
    const chartInvoke = jest.fn(async () => JSON.stringify({ success: true }));
    const toolNode = new ToolNode({
      tools: [
        makeBecauseTool(
          JSON.stringify({ success: false, error: 'database unavailable' })
        ),
        makeEchartsTool(chartInvoke),
      ],
      dispatchSyntheticToolCall: async () => 'step_chart',
    });

    await toolNode.invoke({ messages: [dataCall()] }, indicatorConfig);
    expect(chartInvoke).not.toHaveBeenCalled();
  });

  it('does not treat non-SQL because_jn commands as chart candidates', async () => {
    const chartInvoke = jest.fn(async () => JSON.stringify({ success: true }));
    const toolNode = new ToolNode({
      tools: [
        makeBecauseTool(JSON.stringify({ success: true, rows: [] })),
        makeEchartsTool(chartInvoke),
      ],
      dispatchSyntheticToolCall: async () => 'step_chart',
    });

    await toolNode.invoke(
      { messages: [dataCall('indicator-understanding')] },
      indicatorConfig
    );
    expect(chartInvoke).not.toHaveBeenCalled();
  });
});
