import { AIMessage, ToolMessage } from '@langchain/core/messages';
import { tool } from '@langchain/core/tools';
import { z } from 'zod';
import { ToolNode } from '../ToolNode';
import { ChartRunRegistry } from '../ChartRunRegistry';

type BecauseResult = string;

const indicatorConfig = {
  configurable: {
    auto_chart: true,
    chart_config: {
      preset: 'indicator',
      input_mode: 'simple',
      max_charts: 1,
    },
    requestBody: { text: '查询指标趋势' },
  },
};

function makeBecauseTool(result: BecauseResult) {
  return tool(async () => result, {
    name: 'because_jn',
    description: 'test data tool',
    schema: z.object({
      command: z.string(),
      arguments: z.string().optional(),
    }),
  });
}

function makeEchartsTool(
  invoke: (params: Record<string, unknown>) => Promise<string>
) {
  return tool(invoke, {
    name: 'echarts_generator_app',
    description: 'test chart tool',
    schema: z.object({
      charts: z.array(z.record(z.string(), z.any())),
      _autoGenerated: z.boolean().optional(),
    }),
  });
}

function dataCall(command = 'sql-executor', id = 'call_data') {
  return new AIMessage({
    content: '',
    tool_calls: [
      {
        id,
        name: 'because_jn',
        args: { command, arguments: '{}' },
      },
    ],
  });
}

function makeAskDataTool(result: string) {
  return tool(async () => result, {
    name: 'ask_data_mcp_test',
    description: 'test DAT data tool',
    schema: z.object({ query: z.string() }),
  });
}

function askDataCall() {
  return new AIMessage({
    content: '',
    tool_calls: [
      {
        id: 'call_dat',
        name: 'ask_data_mcp_test',
        args: { query: '查询指标' },
      },
    ],
  });
}

describe('ToolNode indicator auto-chart', () => {
  it('executes the server-side chart tool after deterministic auto success', async () => {
    const chartInvoke = jest.fn(async (params: Record<string, unknown>) =>
      JSON.stringify({
        success: true,
        charts: params.charts,
        echartdata: params.charts,
      })
    );
    const toolNode = new ToolNode({
      tools: [
        makeBecauseTool(
          JSON.stringify({
            success: true,
            rows: [
              { data_dt: '2026-01', index_value: 100 },
              { data_dt: '2026-02', index_value: 120 },
            ],
            columns: ['data_dt', 'index_value'],
          })
        ),
        makeEchartsTool(chartInvoke),
      ],
      dispatchSyntheticToolCall: async () => 'step_chart',
    });

    const result = (await toolNode.invoke(
      { messages: [dataCall()] },
      indicatorConfig
    )) as { messages: ToolMessage[] };

    expect(result.messages).toHaveLength(1);
    expect(chartInvoke).toHaveBeenCalledTimes(1);
    expect(chartInvoke.mock.calls[0][0]).toMatchObject({
      _autoGenerated: true,
    });
  });

  it('does not dispatch the same automatic chart twice when the data call re-enters the node', async () => {
    const chartInvoke = jest.fn(async (params: Record<string, unknown>) =>
      JSON.stringify({ success: true, charts: params.charts, echartdata: params.charts })
    );
    const toolNode = new ToolNode({
      tools: [
        makeBecauseTool(
          JSON.stringify({
            success: true,
            rows: [
              { data_dt: '2026-01', index_value: 100 },
              { data_dt: '2026-02', index_value: 120 },
            ],
          })
        ),
        makeEchartsTool(chartInvoke),
      ],
      chartRunRegistry: new ChartRunRegistry(),
      dispatchSyntheticToolCall: async () => 'step_chart',
    });

    await toolNode.invoke({ messages: [dataCall()] }, indicatorConfig);
    await toolNode.invoke({ messages: [dataCall()] }, indicatorConfig);

    expect(chartInvoke).toHaveBeenCalledTimes(1);
  });

  it('does not register a rejected duplicate synthetic step for another data call', async () => {
    const chartInvoke = jest.fn(async (params: Record<string, unknown>) =>
      JSON.stringify({ success: true, charts: params.charts, echartdata: params.charts })
    );
    const dispatchSyntheticToolCall = jest.fn(async () => 'step_chart');
    const toolNode = new ToolNode({
      tools: [
        makeBecauseTool(
          JSON.stringify({
            success: true,
            rows: [
              { data_dt: '2026-01', index_value: 100 },
              { data_dt: '2026-02', index_value: 120 },
            ],
          })
        ),
        makeEchartsTool(chartInvoke),
      ],
      chartRunRegistry: new ChartRunRegistry(),
      dispatchSyntheticToolCall,
    });

    await toolNode.invoke({ messages: [dataCall('sql-executor', 'call_1')] }, indicatorConfig);
    await toolNode.invoke({ messages: [dataCall('sql-executor', 'call_2')] }, indicatorConfig);

    expect(chartInvoke).toHaveBeenCalledTimes(1);
    expect(dispatchSyntheticToolCall).toHaveBeenCalledTimes(1);
  });

  it('continues automatic chart ids from the conversation offset', async () => {
    const chartInvoke = jest.fn(async (params: Record<string, unknown>) =>
      JSON.stringify({
        success: true,
        charts: params.charts,
        echartdata: params.charts,
      })
    );
    const toolNode = new ToolNode({
      tools: [
        makeBecauseTool(
          JSON.stringify({
            success: true,
            rows: [
              { data_dt: '2026-01', index_value: 100 },
              { data_dt: '2026-02', index_value: 120 },
            ],
          })
        ),
        makeEchartsTool(chartInvoke),
      ],
      dispatchSyntheticToolCall: async () => 'step_chart',
    });

    await toolNode.invoke(
      { messages: [dataCall()] },
      {
        ...indicatorConfig,
        configurable: {
          ...indicatorConfig.configurable,
          chart_id_offset: 3,
        },
      }
    );

    expect(chartInvoke.mock.calls[0][0]).toMatchObject({
      charts: [expect.objectContaining({ id: 'chart_4' })],
      _autoGenerated: true,
    });
  });

  it('uses a stable session-scoped id when conversationId is available', async () => {
    const chartInvoke = jest.fn(async (params: Record<string, unknown>) =>
      JSON.stringify({ success: true, charts: params.charts, echartdata: params.charts })
    );
    const toolNode = new ToolNode({
      tools: [
        makeBecauseTool(JSON.stringify({
          success: true,
          rows: [
            { data_dt: '2026-01', index_value: 100 },
            { data_dt: '2026-02', index_value: 120 },
          ],
        })),
        makeEchartsTool(chartInvoke),
      ],
      dispatchSyntheticToolCall: async () => 'step_chart',
    });

    await toolNode.invoke(
      { messages: [dataCall()] },
      {
        ...indicatorConfig,
        configurable: {
          ...indicatorConfig.configurable,
          chart_index_offset: 2,
          requestBody: {
            text: '查询指标趋势',
            conversationId: 'conversation-123',
          },
        },
      },
    );

    const chart = (chartInvoke.mock.calls[0][0] as { charts: Array<{ id: string }> }).charts[0];
    expect(chart.id).toBe('zb_5c01549bf7a1390c_2');
  });

  it('skips chart generation when the successful data result cannot be parsed', async () => {
    const chartInvoke = jest.fn(async () => JSON.stringify({ success: true }));
    const toolNode = new ToolNode({
      tools: [makeBecauseTool('not-json'), makeEchartsTool(chartInvoke)],
      dispatchSyntheticToolCall: async () => 'step_chart',
    });

    await toolNode.invoke({ messages: [dataCall()] }, indicatorConfig);

    expect(chartInvoke).not.toHaveBeenCalled();
  });

  it('skips chart generation for malformed DAT ask_data output', async () => {
    const chartInvoke = jest.fn(async () => JSON.stringify({ success: true }));
    const toolNode = new ToolNode({
      tools: [
        makeAskDataTool('Query Results: not-json'),
        makeEchartsTool(chartInvoke),
      ],
      dispatchSyntheticToolCall: async () => 'step_chart',
    });

    await toolNode.invoke({ messages: [askDataCall()] }, indicatorConfig);

    expect(chartInvoke).not.toHaveBeenCalled();
  });

  it('skips chart generation when parsed rows have no chartable values', async () => {
    const chartInvoke = jest.fn(async () => JSON.stringify({ success: true }));
    const toolNode = new ToolNode({
      tools: [
        makeBecauseTool(
          JSON.stringify({
            success: true,
            rows: [{ label: 'only text' }],
            columns: ['label'],
          })
        ),
        makeEchartsTool(chartInvoke),
      ],
      dispatchSyntheticToolCall: async () => 'step_chart',
    });

    await toolNode.invoke({ messages: [dataCall()] }, indicatorConfig);

    expect(chartInvoke).not.toHaveBeenCalled();
  });

  it('does not generate a chart when the matched rule is intentionally disabled', async () => {
    const chartInvoke = jest.fn(async () => JSON.stringify({ success: true }));
    const toolNode = new ToolNode({
      tools: [
        makeBecauseTool(JSON.stringify({
          success: true,
          rows: [{ org_name: 'A', index_value: 10 }, { org_name: 'B', index_value: 20 }],
        })),
        makeEchartsTool(chartInvoke),
      ],
      dispatchSyntheticToolCall: async () => 'step_chart',
    });

    await toolNode.invoke({ messages: [dataCall()] }, {
      ...indicatorConfig,
      configurable: {
        ...indicatorConfig.configurable,
        chart_config: {
          ...indicatorConfig.configurable.chart_config,
          match_rules: { dimension_compare: { enabled: false } },
        },
      },
    });

    expect(chartInvoke).not.toHaveBeenCalled();
  });

  it('does not retry when the chart generator itself fails', async () => {
    const chartInvoke = jest.fn(async () =>
      JSON.stringify({ success: false, error: 'generator failed' })
    );
    const toolNode = new ToolNode({
      tools: [
        makeBecauseTool(
          JSON.stringify({
            success: true,
            rows: [
              { data_dt: '2026-01', index_value: 100 },
              { data_dt: '2026-02', index_value: 120 },
            ],
          })
        ),
        makeEchartsTool(chartInvoke),
      ],
      dispatchSyntheticToolCall: async () => 'step_chart',
    });

    await toolNode.invoke({ messages: [dataCall()] }, indicatorConfig);

    expect(chartInvoke).toHaveBeenCalledTimes(1);
  });

  it('does not generate a chart for an explicit SQL execution failure', async () => {
    const chartInvoke = jest.fn(async () => JSON.stringify({ success: true }));
    const toolNode = new ToolNode({
      tools: [
        makeBecauseTool(
          JSON.stringify({ success: false, error: 'database unavailable' })
        ),
        makeEchartsTool(chartInvoke),
      ],
      dispatchSyntheticToolCall: async () => 'step_chart',
    });

    await toolNode.invoke({ messages: [dataCall()] }, indicatorConfig);
    expect(chartInvoke).not.toHaveBeenCalled();
  });

  it('does not treat non-SQL because_jn commands as chart candidates', async () => {
    const chartInvoke = jest.fn(async () => JSON.stringify({ success: true }));
    const toolNode = new ToolNode({
      tools: [
        makeBecauseTool(JSON.stringify({ success: true, rows: [] })),
        makeEchartsTool(chartInvoke),
      ],
      dispatchSyntheticToolCall: async () => 'step_chart',
    });

    await toolNode.invoke(
      { messages: [dataCall('indicator-understanding')] },
      indicatorConfig
    );
    expect(chartInvoke).not.toHaveBeenCalled();
  });
});
